-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 23:11:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ccom4019
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ccom4019
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ccom4019` DEFAULT CHARACTER SET utf8 ;
USE `ccom4019` ;

-- -----------------------------------------------------
-- Table `ccom4019`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ccom4019`.`departments` ;

CREATE TABLE IF NOT EXISTS `ccom4019`.`departments` (
  `dept_id` CHAR(4) NOT NULL,
  `dept_name` VARCHAR(45) NULL,
  PRIMARY KEY (`dept_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccom4019`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ccom4019`.`courses` ;

CREATE TABLE IF NOT EXISTS `ccom4019`.`courses` (
  `course_id` CHAR(8) NOT NULL,
  `course_name` VARCHAR(45) NOT NULL,
  `course_credits` TINYINT(1) UNSIGNED NOT NULL,
  `course_desc` TEXT NULL,
  `dept_id` CHAR(4) NOT NULL REFERENCES departments(dept_id),
  `updated_by` VARCHAR(20) NULL,
  `last_updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccom4019`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ccom4019`.`users` ;

CREATE TABLE IF NOT EXISTS `ccom4019`.`users` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `role` VARCHAR(15) NOT NULL,
  `last_login` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dept_id` CHAR(4) NOT NULL REFERENCES departments(dept_id),
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccom4019`.`prerequisites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ccom4019`.`prerequisites` ;

CREATE TABLE IF NOT EXISTS `ccom4019`.`prerequisites` (
  `course_id` CHAR(8) NOT NULL REFERENCES courses(course_id),
  `prerequisite` CHAR(8) NOT NULL,
  PRIMARY KEY (`course_id`, `prerequisite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccom4019`.`terms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ccom4019`.`terms` ;

CREATE TABLE IF NOT EXISTS `ccom4019`.`terms` (
  `term_id` CHAR(3) NOT NULL,
  `term_desc` VARCHAR(30) NOT NULL,
  `term_is_active` BIT(1) NOT NULL,
  PRIMARY KEY (`term_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccom4019`.`term_offering`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ccom4019`.`term_offering` ;

CREATE TABLE IF NOT EXISTS `ccom4019`.`term_offering` (
  `term_id` CHAR(3) NOT NULL REFERENCES terms(term_id),
  `course_id` CHAR(8) NOT NULL REFERENCES courses(course_id),
  PRIMARY KEY (`term_id`, `course_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
